# Generated by Django 4.1.7 on 2023-04-19 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Asterism",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("asterism_name", models.CharField(max_length=200)),
                (
                    "asterism_desc",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                (
                    "asterism_img",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "asterism_img_2",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Culture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("culture_name", models.CharField(max_length=200)),
                (
                    "geographic_region",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "culture_desc",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                ("culture_img", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "culture_img_2",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Stars",
            fields=[
                ("star_hip", models.IntegerField(primary_key=True, serialize=False)),
                ("star_ra", models.FloatField()),
                ("star_dec", models.FloatField()),
                ("asterisms", models.ManyToManyField(to="asterisms.asterism")),
            ],
        ),
        migrations.AddField(
            model_name="asterism",
            name="culture",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="asterisms.culture"
            ),
        ),
    ]
