# Generated by Django 4.1.7 on 2023-05-10 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("asterisms", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Continent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("continent_name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("region_name", models.CharField(max_length=200)),
                (
                    "continent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="asterisms.continent",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="culture",
            name="geographic_region",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="asterisms.region"
            ),
        ),
    ]
